### ISSUE TITLE
AV1AN doesn't output 10-bit HEVC

### ISSUE THREAD

**Issue by PweSol** [n00mkrad/nmkoder#20]
When I select YUV420PLE or YUV444PLE in AV1AN, the output file is only 8-bit (checked with Mediainfo). Everything else works; the chroma subsampling, 10-bit AV1 and VP9 in AV1AN, 10-bit HEVC in Quick Convert.

**Comment by n00mkrad** [comment]
Looks like an av1an problem, I've opened an issue: https://github.com/master-of-zen/Av1an/issues/572

I could also explicitly set the color format but I can't find what the command line argument for that is.

**Comment by n00mkrad** [comment]
Found the arg, it's `--output-depth`. I will just explicitly set it for now.
