### ISSUE TITLE
[Feature Request] Overwrite stupid av1an max-frame-per-segment from fixed 240 to fps * 10 seconds

### ISSUE THREAD

**Issue by TheThing** [n00mkrad/nmkoder#23]
When dealing with higher fps content like PAL or 30fps or even 50/60fps, the max-frame length per segment should auto be 10 seconds * the framerate since av1an is being stupid about it.

**Comment by n00mkrad** [comment]
Use `-x 300` (or any other number) in av1an custom arguments.
Not sure if I'll set it to FPS*10, I'll think about that.

**Comment by n00mkrad** [comment]
Ok done https://github.com/n00mkrad/nmkoder/commit/6302d8446950e2ab93c559482bcfd39eb378ea0b

**Comment by master-of-zen** [comment]
@TheThing  The stupid, disgusting, brainless av1an 240 extra splits is now fps * 10 .
