### ISSUE TITLE
Output filename not updated on drag and drop

### ISSUE THREAD

**Issue by DejayRezme** [n00mkrad/nmkoder#26]
When I drag and drop a file on nmkoder, the output filename is not updated to be edited until I press start. If you start then cancel the output filename is there. But if you edit the filename it still doesn't get used. 

Tested with 1.10. Related to #10 since that would also affect output filename.

**Comment by n00mkrad** [comment]
Can not reproduce.

Can you show a screen recording of this?

**Comment by DejayRezme** [comment]
Oh. It seems in muxing mode it works, but in batch processing mode it doesn't. Which I guess makes kinda sense, even if you use batch to process only 1 file. Even the thumbnail works now haha.

I guess the only fix would be with some renaming scheme like with #10.

Sorry, not having the best of luck reporting bugs today haha. Closing.

**Comment by n00mkrad** [comment]
Filenames in batch mode are a bit barebones right now, they get auto-filled.

I want to add suffix features for that later.
