### ISSUE TITLE
Resizing video spits out an error

### ISSUE THREAD

**Issue by Bits360** [n00mkrad/nmkoder#28]
I attempted to resize a video from 4k to 1080x1920, but it throws an error saying "source width/height must be at least 64", on encode. This occurs on default settings.

**Comment by trixoniisama** [comment]
I guess you're using SVT-AV1, right ? The error is showing in orange, right ? Unless it actually crashes the encode, then it's _normal_ behaviour, don't be worried by it.

**Comment by Bits360** [comment]
It was crashing, I reinstalled, I dont know why its fixed but that fixed it.
