### ISSUE TITLE
Av1an crash after scene detection

### ISSUE THREAD

**Issue by vertexgamer** [n00mkrad/nmkoder#4]
The only way to not make it crash is to set 1 worker under av1an options. I tried to force -w 1920 -h 1080 under av1an>video>custom arguments, but with no success
[logs.zip](https://github.com/n00mkrad/nmkoder/files/7590650/logs.zip)

https://ibb.co/BKd20xK

**Comment by n00mkrad** [comment]
This means av1an failed to pipe the video data to the encoder.
Seems to be a problem with your input video.
Also make sure you are not running out of RAM.

**Comment by vertexgamer** [comment]
i checked memory usage, total ram usage never exceeds 6,5gb (running 2x16gb)
I know someone who encoded this without a problem, maybe it's a problem on my windows (10) installation
Here is the file if you want to try yourself: https://drive.google.com/file/d/1uYjmPDpfUIrT_KFfpEIkGuo7F7Q34tNj/view?usp=sharing

**Comment by n00mkrad** [comment]
Yeah I encoded that :p 

Can you join the AV1 Discord server? I have a channel for nmkoder there and there's also one for av1an.

https://discord.com/invite/HSBxne3

**Comment by n00mkrad** [comment]
Closing as this is related to the input file being broken, not an Nmkoder issue.
